// src/lib/locations.ts
export interface LocationFAQ { question: string; answer: string; }

export interface LocationData {
  slug: string;
  name: string;
  description: string;
  landmarks: string[];
  nearbyAreas: string[];
  faqs: LocationFAQ[];
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
}

function loc(
  slug: string,
  name: string,
  description: string,
  landmarks: string[],
  nearbyAreas: string[],
  faqs: LocationFAQ[],
): LocationData {
  return {
    slug,
    name,
    description,
    landmarks,
    nearbyAreas,
    faqs,
    metaTitle: `Appliance Repair in ${name} Dharwad | Hosatti Refrigeration`,
    metaDescription: `AC, fridge & washing machine repair in ${name}, Dharwad by Hosatti. Doorstep or walk-in workshop service. Call +91-7899472430 — quick available!`,
    keywords: [
      `AC repair ${name} Dharwad`,
      `fridge repair ${name} Dharwad`,
      `washing machine repair ${name} Dharwad`,
      `appliance repair ${name} Dharwad`,
      `air cooler repair ${name} Dharwad`,
      `refrigerator repair ${name} Dharwad`,
      `AC service ${name} Dharwad`,
      `home appliance repair ${name} Dharwad`,
    ],
  };
}

function faq(q: string, a: string): LocationFAQ { return { question: q, answer: a }; }

export const LOCATIONS: LocationData[] = [
  loc(
    "jayanagar-dharwad",
    "Jayanagar",
    "Jayanagar is a bustling, well-connected residential area in Dharwad, home to a large number of families who rely on quality appliance repair services. Residents of Jayanagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Jayanagar. Hosatti Refrigeration Service has been serving Jayanagar households with expert AC, refrigerator, washing machine, and air cooler repair for over 15 years.",
    ["Jayanagar Circle", "Local bus stop", "Jayanagar park"],
    ["Saptapur", "Jay Nagar", "CB Nagar"],
    [
      faq("Is there AC repair service in Jayanagar, Dharwad?", "Yes, Hosatti Refrigeration Service provides doorstep AC repair in Jayanagar, Dharwad. Call or WhatsApp +91-7899472430 for quick service."),
      faq("Who repairs refrigerators in Jayanagar, Dharwad?", "Hosatti Refrigeration Service repairs all brands of refrigerators in Jayanagar, Dharwad. Our technician visits your home or you can bring it to our Jay Nagar workshop."),
      faq("Is washing machine repair available in Jayanagar, Dharwad?", "Yes, we provide fully automatic and semi-automatic washing machine repair in Jayanagar. Call +91-7899472430 for doorstep service."),
      faq("How far is your workshop from Jayanagar, Dharwad?", "Our workshop at Jay Nagar, Dharwad is just a few minutes from Jayanagar. You can bring your appliance directly to us or we can come to your home."),
      faq("Do you service air coolers in Jayanagar, Dharwad?", "Yes, we repair all brands of air coolers in Jayanagar, Dharwad — cooling pad replacement, pump repair, motor repair, and more."),
    ],
  ),
  loc(
    "saptapur-dharwad",
    "Saptapur",
    "Saptapur is a prominent area in Dharwad located very close to our workshop at Jay Nagar, making it one of our fastest-served neighborhoods. Residents of Saptapur can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Saptapur in just minutes. Our skilled technicians have served hundreds of Saptapur families with reliable AC, fridge, and washing machine repairs.",
    ["Saptapur Last Stop", "Gurukul Academy", "Saptapur main road"],
    ["Jay Nagar", "Jayanagar", "CB Nagar"],
    [
      faq("Is there AC repair service in Saptapur, Dharwad?", "Yes, Saptapur is one of our closest service areas. Our workshop is located right at Saptapur Last Stop, Jay Nagar. Call +91-7899472430 for immediate service."),
      faq("Who does fridge repair in Saptapur, Dharwad?", "Hosatti Refrigeration Service provides expert fridge repair in Saptapur — by far the nearest professional repair service to this area."),
      faq("Can I bring my washing machine to your workshop from Saptapur?", "Absolutely. Our workshop is at Saptapur Last Stop, Jay Nagar, Dharwad — just minutes from Saptapur. Bring your appliance or call for doorstep service."),
      faq("Do you repair air coolers in Saptapur, Dharwad?", "Yes, we repair all air cooler brands in Saptapur with quick doorstep service available."),
      faq("What is your address near Saptapur, Dharwad?", "Jaya Nagar, Opp Gurukul Academy, Saptapur Last Stop, Jay Nagar, Dharwad – 580001. Call +91-7899472430."),
    ],
  ),
  loc(
    "jay-nagar-dharwad",
    "Jay Nagar",
    "Jay Nagar is where Hosatti Refrigeration Service's main workshop is located, making it the fastest-served area in all of Dharwad. Our workshop is at Jaya Nagar, Opp Gurukul Academy, Saptapur Last Stop — you can walk in directly for quick appliance repair. Residents of Jay Nagar enjoy the advantage of having Dharwad's most trusted appliance repair expert literally at their doorstep, with no waiting for a technician visit.",
    ["Gurukul Academy", "Saptapur Last Stop", "Jay Nagar main road"],
    ["Saptapur", "Jayanagar", "Adishakti Colony"],
    [
      faq("Where is Hosatti Refrigeration Service workshop in Jay Nagar?", "Our workshop is at Jaya Nagar, Opp Gurukul Academy, Saptapur Last Stop, Jay Nagar, Dharwad – 580001. Walk in anytime during business hours."),
      faq("Can I get quick AC repair in Jay Nagar, Dharwad?", "Yes, Jay Nagar is our home area — quick repair is almost always possible. Call +91-7899472430 early for priority scheduling."),
      faq("Do you do doorstep fridge repair in Jay Nagar?", "Yes, we come to your home in Jay Nagar for refrigerator repair, or you can bring it to our nearby workshop."),
      faq("Is your workshop open on Sunday in Jay Nagar, Dharwad?", "Yes, we are open Sunday 9:30 AM – 1:00 PM. Mon–Sat 9:30 AM – 7:00 PM."),
      faq("Who is the best appliance repair technician in Jay Nagar, Dharwad?", "Hosatti Refrigeration Service, led by Jameer Hosatti with 15+ years of experience, is the go-to appliance repair expert in Jay Nagar, Dharwad."),
    ],
  ),
  loc(
    "cb-nagar-dharwad",
    "CB Nagar",
    "CB Nagar is a well-established residential colony in Dharwad, known for its close-knit community and growing households. Residents of CB Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from CB Nagar. We regularly serve CB Nagar families with AC repair, refrigerator repair, washing machine service, and air cooler repair.",
    ["CB Nagar main road", "Local market", "CB Nagar park"],
    ["Jayanagar", "Saptapur", "Adishakti Colony"],
    [
      faq("Is there appliance repair service in CB Nagar, Dharwad?", "Yes, Hosatti Refrigeration Service provides doorstep AC, fridge, washing machine, and cooler repair in CB Nagar, Dharwad. Call +91-7899472430."),
      faq("Who does AC repair in CB Nagar, Dharwad?", "Our skilled technicians cover CB Nagar for all AC brands. Quick service is available — call +91-7899472430 early."),
      faq("Is refrigerator repair available in CB Nagar, Dharwad?", "Yes, we provide doorstep or walk-in fridge repair for CB Nagar residents. All brands serviced."),
      faq("Do you repair washing machines in CB Nagar, Dharwad?", "Yes — fully automatic, semi-automatic, front-load, and top-load washing machines all serviced in CB Nagar."),
      faq("How do I book appliance repair in CB Nagar, Dharwad?", "Call or WhatsApp +91-7899472430. Our technician will visit your home in CB Nagar or you can bring your appliance to our Jay Nagar workshop."),
    ],
  ),
  loc(
    "adishakti-colony-dharwad",
    "Adishakti Colony",
    "Adishakti Colony is a quiet residential area in Dharwad with families who trust Hosatti Refrigeration Service for all their home appliance repair needs. Residents of Adishakti Colony can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Adishakti Colony. We bring the same professional service that Dharwad has trusted for 15+ years right to your door.",
    ["Adishakti Colony entrance", "Nearby school", "Local temple"],
    ["Jay Nagar", "CB Nagar", "Pagan Nagar"],
    [
      faq("Do you provide AC repair in Adishakti Colony, Dharwad?", "Yes, we provide doorstep AC repair for all brands in Adishakti Colony, Dharwad. Call +91-7899472430 for quick service."),
      faq("Is fridge repair available in Adishakti Colony, Dharwad?", "Yes, our technicians visit homes in Adishakti Colony for refrigerator repair and also accept walk-ins at our Jay Nagar workshop."),
      faq("Who repairs washing machines in Adishakti Colony, Dharwad?", "Hosatti Refrigeration Service provides fully automatic and semi-automatic washing machine repair in Adishakti Colony with doorstep service."),
      faq("Is air cooler repair available in Adishakti Colony, Dharwad?", "Yes, we repair all brands of air coolers in Adishakti Colony including Symphony, Bajaj, Crompton, and more."),
      faq("How quickly can you reach Adishakti Colony from your workshop?", "Our Jay Nagar workshop is very close to Adishakti Colony. We typically reach within 30–60 minutes of your call."),
    ],
  ),
  loc(
    "pagan-nagar-dharwad",
    "Pagan Nagar",
    "Pagan Nagar is a growing residential area in Dharwad where Hosatti Refrigeration Service has built a strong reputation for reliable, honest appliance repair. Residents of Pagan Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Pagan Nagar. From AC repairs during summer to refrigerator fixes all year round, we are Dharwad's trusted choice.",
    ["Pagan Nagar main road", "Local mosque", "Neighborhood market"],
    ["Jay Nagar", "Adishakti Colony", "Keshav Nagar"],
    [
      faq("Is there AC repair service in Pagan Nagar, Dharwad?", "Yes, Hosatti provides doorstep AC repair in Pagan Nagar, Dharwad. Call +91-7899472430 for fast service."),
      faq("Who repairs LG and Samsung fridges in Pagan Nagar, Dharwad?", "We repair all brands including LG, Samsung, Godrej, Whirlpool, and more in Pagan Nagar with doorstep service."),
      faq("Is washing machine repair available in Pagan Nagar, Dharwad?", "Yes, fully automatic and semi-automatic washing machine repair is available in Pagan Nagar with quick doorstep service."),
      faq("Do you provide air cooler motor repair in Pagan Nagar, Dharwad?", "Yes, we repair and replace air cooler motors for all brands in Pagan Nagar, Dharwad."),
      faq("What is the fastest way to book appliance repair in Pagan Nagar?", "WhatsApp +91-7899472430 for the fastest response. Our technician will visit your Pagan Nagar home at your convenience."),
    ],
  ),
  loc(
    "keshav-nagar-dharwad",
    "Keshav Nagar",
    "Keshav Nagar is a well-populated residential neighborhood in Dharwad with a high concentration of families who count on Hosatti Refrigeration Service for prompt appliance repairs. Residents of Keshav Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Keshav Nagar. We service all 12 major appliance categories with genuine parts and warranty.",
    ["Keshav Nagar circle", "Local school", "Community center"],
    ["Pagan Nagar", "Jay Nagar", "Shreyas Colony"],
    [
      faq("Is AC repair available in Keshav Nagar, Dharwad?", "Yes, we provide doorstep AC repair for all brands in Keshav Nagar. Call +91-7899472430 for quick service."),
      faq("Who repairs refrigerators in Keshav Nagar, Dharwad?", "Hosatti Refrigeration Service provides expert fridge repair in Keshav Nagar with quick doorstep service."),
      faq("Do you repair washing machines in Keshav Nagar, Dharwad?", "Yes, all types of washing machines are repaired in Keshav Nagar by our skilled technicians."),
      faq("Is air cooler repair available in Keshav Nagar, Dharwad?", "Yes, cooler pad replacement, pump repair, and motor repair available in Keshav Nagar."),
      faq("How do I contact Hosatti Refrigeration for Keshav Nagar service?", "Call or WhatsApp +91-7899472430. Doorstep service or visit our Jay Nagar workshop."),
    ],
  ),
  loc(
    "shreyas-colony-dharwad",
    "Shreyas Colony",
    "Shreyas Colony is a pleasant residential colony in Dharwad where homeowners consistently choose Hosatti Refrigeration Service for dependable appliance repair. Residents of Shreyas Colony can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Shreyas Colony. Whether it's a summer AC breakdown or a fridge not cooling, our team arrives fast with genuine parts.",
    ["Shreyas Colony entrance", "Nearby hospital", "Local market"],
    ["Keshav Nagar", "Jay Nagar", "Vidyanagar"],
    [
      faq("Is appliance repair available in Shreyas Colony, Dharwad?", "Yes, Hosatti Refrigeration Service provides complete AC, fridge, washing machine, and cooler repair in Shreyas Colony, Dharwad."),
      faq("Who does doorstep AC service in Shreyas Colony, Dharwad?", "Our skilled technicians provide doorstep AC repair and deep cleaning for all brands in Shreyas Colony."),
      faq("Do you repair Whirlpool and Samsung fridges in Shreyas Colony?", "Yes, we repair all brands including Whirlpool, Samsung, LG, Godrej, and Haier in Shreyas Colony."),
      faq("Is washing machine repair available quick in Shreyas Colony, Dharwad?", "Quick washing machine repair is available in Shreyas Colony when you call early. WhatsApp +91-7899472430."),
      faq("How far is Shreyas Colony from your workshop in Dharwad?", "Our Jay Nagar workshop is easily accessible from Shreyas Colony — you can drop off appliances or call for home service."),
    ],
  ),
  loc(
    "vidyanagar-dharwad",
    "Vidyanagar",
    "Vidyanagar is one of Dharwad's largest and most prominent residential areas, housing thousands of families who depend on Hosatti Refrigeration Service for professional appliance repair. Residents of Vidyanagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Vidyanagar. With 15+ years serving Dharwad, we are Vidyanagar's most trusted appliance repair expert.",
    ["Karnataka University", "Vidyanagar Bus Stand", "Vidyanagar main market", "Medical college"],
    ["Vidyagiri", "Shivaji Nagar", "Kalyan Nagar"],
    [
      faq("Is there AC repair service in Vidyanagar, Dharwad?", "Yes, Hosatti Refrigeration Service provides doorstep AC repair for all brands in Vidyanagar, Dharwad. Call +91-7899472430 for quick service."),
      faq("Who is the best fridge repair technician in Vidyanagar, Dharwad?", "Hosatti Refrigeration Service, with 15+ years of experience, is the most trusted fridge repair service in Vidyanagar, Dharwad."),
      faq("Is IFB washing machine repair available in Vidyanagar, Dharwad?", "Yes, we repair IFB, LG, Samsung, Whirlpool, Bosch, and all other washing machine brands in Vidyanagar."),
      faq("Do you provide AC gas refilling in Vidyanagar, Dharwad?", "Yes, our technicians provide AC gas refilling and leak repair for all AC brands in Vidyanagar, Dharwad."),
      faq("Can I get air cooler repair in Vidyanagar, Dharwad?", "Yes, we repair all brands of air coolers in Vidyanagar including Symphony, Bajaj, Crompton, and Orient."),
    ],
  ),
  loc(
    "vidyagiri-dharwad",
    "Vidyagiri",
    "Vidyagiri is a well-developed residential and educational area in Dharwad with a large population of homeowners who trust Hosatti Refrigeration Service for all appliance repair needs. Residents of Vidyagiri can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Vidyagiri. Our 15+ years of trusted service in Dharwad means you always get expert help.",
    ["Vidyagiri Circle", "Engineering colleges", "Vidyagiri market"],
    ["Vidyanagar", "Shivaji Nagar", "Sadankeri"],
    [
      faq("Is there doorstep AC repair in Vidyagiri, Dharwad?", "Yes, we provide doorstep AC repair in Vidyagiri for all brands. Call +91-7899472430."),
      faq("Who repairs refrigerators in Vidyagiri, Dharwad?", "Hosatti Refrigeration Service provides expert fridge repair in Vidyagiri with genuine parts and warranty."),
      faq("Is washing machine repair available in Vidyagiri, Dharwad?", "Yes, all washing machine types and brands are serviced in Vidyagiri by our skilled team."),
      faq("Do you provide AC deep cleaning in Vidyagiri, Dharwad?", "Yes, we provide professional AC deep cleaning in Vidyagiri to improve cooling efficiency and air quality."),
      faq("How do I book appliance repair in Vidyagiri, Dharwad?", "Call or WhatsApp +91-7899472430. We'll send a technician to your Vidyagiri home."),
    ],
  ),
  loc(
    "shivaji-nagar-dharwad",
    "Shivaji Nagar",
    "Shivaji Nagar is a thriving residential locality in Dharwad where Hosatti Refrigeration Service has been the preferred choice for appliance repairs for over 15 years. Residents of Shivaji Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Shivaji Nagar. We handle AC not-cooling issues, fridge compressor problems, washing machine drain faults, and cooler motor failures.",
    ["Shivaji Nagar Circle", "Local police station", "Neighborhood park"],
    ["Vidyanagar", "Kalyan Nagar", "Bharati Nagar"],
    [
      faq("Is AC repair service available in Shivaji Nagar, Dharwad?", "Yes, Hosatti Refrigeration Service provides doorstep AC repair in Shivaji Nagar for all brands. Call +91-7899472430."),
      faq("Who does refrigerator repair in Shivaji Nagar, Dharwad?", "Our certified technicians repair all fridge brands in Shivaji Nagar — LG, Samsung, Godrej, Whirlpool, and more."),
      faq("Is AC gas refilling available in Shivaji Nagar, Dharwad?", "Yes, we perform AC gas refilling and leak repair in Shivaji Nagar for all AC types."),
      faq("Do you fix washing machine drain problems in Shivaji Nagar?", "Yes, drain pump issues, filter clogs, and hose problems are fixed in Shivaji Nagar with quick service."),
      faq("How quickly can your technician reach Shivaji Nagar, Dharwad?", "Our Jay Nagar workshop is accessible from Shivaji Nagar. Most service calls are attended within 1–2 hours. Call +91-7899472430."),
    ],
  ),
  loc(
    "kalyan-nagar-dharwad",
    "Kalyan Nagar",
    "Kalyan Nagar is a popular residential neighborhood in Dharwad with families who rely on Hosatti Refrigeration Service for fast and reliable appliance repair. Residents of Kalyan Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Kalyan Nagar. From AC installation to fridge compressor repair, our team handles everything.",
    ["Kalyan Nagar park", "Local temple", "Main commercial road"],
    ["Shivaji Nagar", "Bharati Nagar", "Vidyanagar"],
    [
      faq("Is appliance repair available in Kalyan Nagar, Dharwad?", "Yes, Hosatti Refrigeration Service provides AC, fridge, washing machine, and cooler repair in Kalyan Nagar, Dharwad."),
      faq("Who repairs Voltas and Daikin ACs in Kalyan Nagar, Dharwad?", "We repair all AC brands in Kalyan Nagar including Voltas, Daikin, LG, Samsung, Blue Star, and Hitachi."),
      faq("Is quick fridge repair available in Kalyan Nagar, Dharwad?", "Quick fridge repair is available in Kalyan Nagar for most problems. Call +91-7899472430 early."),
      faq("Do you repair IFB washing machines in Kalyan Nagar, Dharwad?", "Yes, we service IFB, Bosch, LG, Samsung, and all other washing machine brands in Kalyan Nagar."),
      faq("Can I visit your workshop from Kalyan Nagar, Dharwad?", "Yes, our workshop at Jay Nagar, Dharwad is accessible from Kalyan Nagar. Bring your appliance or call for home service."),
    ],
  ),
  loc(
    "bharati-nagar-dharwad",
    "Bharati Nagar",
    "Bharati Nagar is a well-established residential area in Dharwad where Hosatti Refrigeration Service is known for prompt, professional appliance repair. Residents of Bharati Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Bharati Nagar. Summer AC breakdowns and fridge cooling issues are resolved swiftly by our expert team.",
    ["Bharati Nagar lane", "Nearby school", "Local grocery market"],
    ["Kalyan Nagar", "Shivaji Nagar", "Sanmati Nagar"],
    [
      faq("Is AC repair available in Bharati Nagar, Dharwad?", "Yes, doorstep AC repair for all brands available in Bharati Nagar. Call +91-7899472430."),
      faq("Who does fridge repair in Bharati Nagar, Dharwad?", "Hosatti Refrigeration Service provides expert fridge repair in Bharati Nagar with quick service options."),
      faq("Is washing machine repair in Bharati Nagar quick?", "Yes, most washing machine repairs in Bharati Nagar are completed quick. WhatsApp +91-7899472430 to book."),
      faq("Do you do AC installation in Bharati Nagar, Dharwad?", "Yes, we install all AC brands in Bharati Nagar with professional mounting and gas checking."),
      faq("Is air cooler repair available in Bharati Nagar, Dharwad?", "Yes, cooler pad replacement, pump fix, and motor repair available in Bharati Nagar."),
    ],
  ),
  loc(
    "sanmati-nagar-dharwad",
    "Sanmati Nagar",
    "Sanmati Nagar is a peaceful residential colony in Dharwad where families trust Hosatti Refrigeration Service for dependable appliance repair year-round. Residents of Sanmati Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Sanmati Nagar. Genuine parts and expert service for every appliance type.",
    ["Sanmati Nagar entrance", "Community hall", "Local temple"],
    ["Bharati Nagar", "Rani Chennamma Nagar", "Lingaraj Nagar"],
    [
      faq("Is there AC service in Sanmati Nagar, Dharwad?", "Yes, Hosatti provides doorstep AC repair, deep cleaning, and gas refilling in Sanmati Nagar, Dharwad."),
      faq("Who repairs refrigerators in Sanmati Nagar, Dharwad?", "Our skilled technicians visit Sanmati Nagar for all fridge brands — LG, Samsung, Godrej, Whirlpool, Haier, and more."),
      faq("Is washing machine repair available in Sanmati Nagar?", "Yes, fully automatic and semi-automatic washing machine repair is available in Sanmati Nagar."),
      faq("Do you repair air coolers in Sanmati Nagar, Dharwad?", "Yes, all air cooler brands serviced in Sanmati Nagar including pad and pump replacement."),
      faq("How do I contact you for Sanmati Nagar, Dharwad service?", "Call or WhatsApp +91-7899472430 for doorstep service in Sanmati Nagar."),
    ],
  ),
  loc(
    "rani-chennamma-nagar-dharwad",
    "Rani Chennamma Nagar",
    "Rani Chennamma Nagar is a large, vibrant residential area in Dharwad named after the legendary queen, and its residents rely on Hosatti Refrigeration Service for expert appliance repairs. Residents of Rani Chennamma Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Rani Chennamma Nagar. We bring 15+ years of trusted appliance expertise directly to your door.",
    ["Rani Chennamma Nagar main road", "Local school", "Community park", "Market area"],
    ["Sanmati Nagar", "Lingaraj Nagar", "Sampige Nagar"],
    [
      faq("Is AC repair available in Rani Chennamma Nagar, Dharwad?", "Yes, doorstep AC repair for all brands in Rani Chennamma Nagar. Call +91-7899472430."),
      faq("Who does fridge repair in Rani Chennamma Nagar, Dharwad?", "Hosatti Refrigeration Service provides expert refrigerator repair in Rani Chennamma Nagar with quick service."),
      faq("Is washing machine repair available in Rani Chennamma Nagar?", "Yes, we repair all washing machine types in Rani Chennamma Nagar — doorstep or walk-in."),
      faq("Do you repair ACs without cooling in Rani Chennamma Nagar?", "Yes, AC not-cooling repair is one of our most common services in Rani Chennamma Nagar."),
      faq("Is air cooler repair available in Rani Chennamma Nagar, Dharwad?", "Yes, all cooler brands serviced in Rani Chennamma Nagar. Call +91-7899472430."),
    ],
  ),
  loc(
    "lingaraj-nagar-dharwad",
    "Lingaraj Nagar",
    "Lingaraj Nagar is a cosmopolitan residential area in Dharwad where Hosatti Refrigeration Service has earned a strong reputation for honest, skilled appliance repair. Residents of Lingaraj Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Lingaraj Nagar. AC, refrigerator, washing machine, and air cooler — we do it all.",
    ["Lingaraj Nagar circle", "Lingaraj Temple vicinity", "Local market"],
    ["Rani Chennamma Nagar", "Sampige Nagar", "Srinagar"],
    [
      faq("Is AC repair service available in Lingaraj Nagar, Dharwad?", "Yes, doorstep AC repair for all brands in Lingaraj Nagar, Dharwad. Call +91-7899472430."),
      faq("Who repairs refrigerators in Lingaraj Nagar, Dharwad?", "Hosatti Refrigeration Service provides complete fridge repair in Lingaraj Nagar with genuine parts."),
      faq("Do you do washing machine repair in Lingaraj Nagar, Dharwad?", "Yes, fully automatic and semi-automatic washing machine repair available in Lingaraj Nagar."),
      faq("Is fridge compressor repair available in Lingaraj Nagar?", "Yes, we diagnose and replace fridge compressors for all brands in Lingaraj Nagar."),
      faq("How do I book repair service in Lingaraj Nagar, Dharwad?", "Call or WhatsApp +91-7899472430 for doorstep service in Lingaraj Nagar."),
    ],
  ),
  loc(
    "sampige-nagar-dharwad",
    "Sampige Nagar",
    "Sampige Nagar is a residential locality in Dharwad with a community that values reliable appliance repair from trusted experts like Hosatti Refrigeration Service. Residents of Sampige Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Sampige Nagar. Expert AC, refrigerator, and washing machine repair with genuine parts.",
    ["Sampige Nagar road", "Local school", "Neighborhood temple"],
    ["Lingaraj Nagar", "Srinagar", "Tejaswi Nagar"],
    [
      faq("Is appliance repair available in Sampige Nagar, Dharwad?", "Yes, Hosatti provides AC, fridge, washing machine, and cooler repair in Sampige Nagar, Dharwad."),
      faq("Who does AC deep cleaning in Sampige Nagar, Dharwad?", "Our team provides professional AC deep cleaning in Sampige Nagar to improve cooling and air quality."),
      faq("Is fridge repair available in Sampige Nagar, Dharwad?", "Yes, we repair all fridge brands in Sampige Nagar with doorstep service."),
      faq("Do you repair washing machines in Sampige Nagar, Dharwad?", "Yes, all types of washing machines are repaired in Sampige Nagar by our skilled technicians."),
      faq("How do I reach Hosatti workshop from Sampige Nagar, Dharwad?", "Our Jay Nagar workshop is accessible from Sampige Nagar. Call +91-7899472430 for directions or home service."),
    ],
  ),
  loc(
    "srinagar-dharwad",
    "Srinagar",
    "Srinagar is a well-known residential area in Dharwad where Hosatti Refrigeration Service has been providing reliable appliance repair for many years. Residents of Srinagar, Dharwad can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Srinagar. We service all 24 major appliance brands with genuine parts and service warranty.",
    ["Srinagar Circle", "Local mosque", "Main road", "Neighborhood market"],
    ["Sampige Nagar", "Tejaswi Nagar", "Sadankeri"],
    [
      faq("Is AC repair available in Srinagar, Dharwad?", "Yes, Hosatti provides doorstep AC repair in Srinagar for all brands. Call +91-7899472430."),
      faq("Who repairs refrigerators in Srinagar, Dharwad?", "We repair all fridge brands in Srinagar — LG, Samsung, Godrej, Whirlpool, and more — with doorstep service."),
      faq("Is AC gas refilling available in Srinagar, Dharwad?", "Yes, AC gas refilling and leak repair service available in Srinagar, Dharwad."),
      faq("Do you do washing machine repair in Srinagar, Dharwad?", "Yes, fully automatic and semi-automatic washing machine repairs available in Srinagar."),
      faq("Is quick repair available in Srinagar, Dharwad?", "Yes, quick appliance repair is available in Srinagar when you call early. WhatsApp +91-7899472430."),
    ],
  ),
  loc(
    "tejaswi-nagar-dharwad",
    "Tejaswi Nagar",
    "Tejaswi Nagar is a growing residential neighborhood in Dharwad where Hosatti Refrigeration Service is the first call for any appliance problem. Residents of Tejaswi Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Tejaswi Nagar. AC repair, fridge repair, and washing machine service — all with guaranteed quality.",
    ["Tejaswi Nagar road", "Local school", "Community park"],
    ["Srinagar", "Sadankeri", "KHB Colony"],
    [
      faq("Is appliance repair available in Tejaswi Nagar, Dharwad?", "Yes, doorstep AC, fridge, washing machine, and cooler repair available in Tejaswi Nagar, Dharwad."),
      faq("Who does AC repair in Tejaswi Nagar, Dharwad?", "Hosatti Refrigeration Service covers Tejaswi Nagar for all AC brands. Call +91-7899472430."),
      faq("Is fridge repair available in Tejaswi Nagar, Dharwad?", "Yes, we repair all refrigerator brands in Tejaswi Nagar with doorstep service."),
      faq("Do you service washing machines in Tejaswi Nagar, Dharwad?", "Yes, all washing machine types serviced in Tejaswi Nagar."),
      faq("How do I contact Hosatti for Tejaswi Nagar, Dharwad?", "Call or WhatsApp +91-7899472430 for doorstep service in Tejaswi Nagar."),
    ],
  ),
  loc(
    "sadankeri-dharwad",
    "Sadankeri",
    "Sadankeri is one of Dharwad's established residential areas with a loyal community that trusts Hosatti Refrigeration Service for all appliance repair needs. Residents of Sadankeri can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Sadankeri. Fifteen-plus years of expert repair with transparent pricing.",
    ["Sadankeri Lake", "Main road", "Local market", "School area"],
    ["Tejaswi Nagar", "KHB Colony", "Vidyagiri"],
    [
      faq("Is AC repair available in Sadankeri, Dharwad?", "Yes, Hosatti provides doorstep AC repair for all brands in Sadankeri, Dharwad. Call +91-7899472430."),
      faq("Who repairs refrigerators in Sadankeri, Dharwad?", "Our technicians visit Sadankeri for all fridge brands and types — single door, double door, and frost-free."),
      faq("Is washing machine repair available in Sadankeri, Dharwad?", "Yes, all washing machine repairs available in Sadankeri with quick service options."),
      faq("Do you repair air coolers in Sadankeri, Dharwad?", "Yes, all cooler brands repaired in Sadankeri — pads, pumps, motors."),
      faq("Can I visit your workshop from Sadankeri, Dharwad?", "Yes, our Jay Nagar workshop is accessible from Sadankeri. You can bring your appliance or call for home service."),
    ],
  ),
  loc(
    "khb-colony-dharwad",
    "KHB Colony",
    "KHB Colony is a planned residential area in Dharwad developed by the Karnataka Housing Board, home to many families who rely on Hosatti Refrigeration Service for trusted appliance repair. Residents of KHB Colony can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from KHB Colony. Expert technicians, genuine parts, and service warranty.",
    ["KHB Colony entrance", "Community park", "Local school", "Main road"],
    ["Sadankeri", "Ramanagar", "Tejaswi Nagar"],
    [
      faq("Is AC repair available in KHB Colony, Dharwad?", "Yes, Hosatti provides doorstep AC repair in KHB Colony for all brands. Call +91-7899472430."),
      faq("Who repairs fridges in KHB Colony, Dharwad?", "Our skilled technicians repair all fridge brands in KHB Colony with genuine parts and warranty."),
      faq("Is washing machine repair quick in KHB Colony, Dharwad?", "Yes, quick washing machine repair is available in KHB Colony when you call early."),
      faq("Do you install new ACs in KHB Colony, Dharwad?", "Yes, we install all AC brands in KHB Colony with professional setup and testing."),
      faq("Is air cooler repair available in KHB Colony, Dharwad?", "Yes, all cooler brands serviced in KHB Colony including Symphony, Bajaj, and Crompton."),
    ],
  ),
  loc(
    "ramanagar-dharwad",
    "Ramanagar",
    "Ramanagar is a residential locality in Dharwad where Hosatti Refrigeration Service has established itself as the go-to appliance repair expert. Residents of Ramanagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Ramanagar. AC repair, fridge gas filling, washing machine repair — all under one trusted brand.",
    ["Ramanagar road", "Local temple", "Neighborhood school"],
    ["KHB Colony", "Shakti Nagar", "Sadankeri"],
    [
      faq("Is appliance repair available in Ramanagar, Dharwad?", "Yes, Hosatti provides complete appliance repair services in Ramanagar, Dharwad."),
      faq("Who does AC repair in Ramanagar, Dharwad?", "Hosatti Refrigeration Service provides doorstep AC repair in Ramanagar for all brands."),
      faq("Is fridge repair available in Ramanagar, Dharwad?", "Yes, we repair all fridge brands in Ramanagar with doorstep and walk-in options."),
      faq("Do you do washing machine repair in Ramanagar, Dharwad?", "Yes, fully automatic and semi-automatic washing machine repair in Ramanagar."),
      faq("How do I contact Hosatti for Ramanagar, Dharwad service?", "Call or WhatsApp +91-7899472430 for service in Ramanagar."),
    ],
  ),
  loc(
    "shakti-nagar-dharwad",
    "Shakti Nagar",
    "Shakti Nagar is a lively residential colony in Dharwad where residents trust Hosatti Refrigeration Service for prompt and professional appliance repair. Residents of Shakti Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Shakti Nagar. We handle everything from AC gas refilling to washing machine motor repair.",
    ["Shakti Nagar main road", "Local market", "Community hall"],
    ["Ramanagar", "Daneshwari Nagar", "KHB Colony"],
    [
      faq("Is AC repair available in Shakti Nagar, Dharwad?", "Yes, doorstep AC repair for all brands in Shakti Nagar. Call +91-7899472430."),
      faq("Who repairs refrigerators in Shakti Nagar, Dharwad?", "Hosatti Refrigeration Service is the trusted fridge repair expert in Shakti Nagar, Dharwad."),
      faq("Is washing machine repair available in Shakti Nagar?", "Yes, all washing machine types serviced in Shakti Nagar with quick options."),
      faq("Do you provide AC deep cleaning in Shakti Nagar, Dharwad?", "Yes, professional AC deep cleaning available in Shakti Nagar to restore cooling."),
      faq("Is air cooler repair available in Shakti Nagar, Dharwad?", "Yes, cooler pad, pump, and motor repairs all available in Shakti Nagar."),
    ],
  ),
  loc(
    "daneshwari-nagar-dharwad",
    "Daneshwari Nagar",
    "Daneshwari Nagar is a growing residential area in Dharwad with families who count on Hosatti Refrigeration Service for their appliance repair needs. Residents of Daneshwari Nagar can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Daneshwari Nagar. Professional service backed by 15+ years of Dharwad expertise.",
    ["Daneshwari Nagar road", "Local school", "Community park"],
    ["Shakti Nagar", "Akashavani Road", "Ramanagar"],
    [
      faq("Is appliance repair in Daneshwari Nagar, Dharwad available?", "Yes, Hosatti provides AC, fridge, washing machine, and cooler repair in Daneshwari Nagar."),
      faq("Who does AC repair in Daneshwari Nagar, Dharwad?", "Hosatti Refrigeration Service provides doorstep AC repair in Daneshwari Nagar for all brands."),
      faq("Is fridge repair available in Daneshwari Nagar, Dharwad?", "Yes, we repair all fridge brands in Daneshwari Nagar with genuine parts."),
      faq("Do you repair washing machines in Daneshwari Nagar, Dharwad?", "Yes, all washing machine types repaired in Daneshwari Nagar."),
      faq("How far is your workshop from Daneshwari Nagar, Dharwad?", "Our Jay Nagar workshop is a short drive from Daneshwari Nagar. Call +91-7899472430 for home service."),
    ],
  ),
  loc(
    "akashavani-road-dharwad",
    "Akashavani Road",
    "Akashavani Road is one of Dharwad's prominent stretches with residential and commercial properties, where Hosatti Refrigeration Service is the trusted name for all appliance repairs. Residents and businesses on Akashavani Road can call our team for doorstep appliance repair at their home or establishment, or visit our workshop directly at Jay Nagar, Dharwad. Named after the iconic All India Radio station nearby, this is a key artery of Dharwad we serve with pride.",
    ["All India Radio (AIR) Dharwad", "Akashavani station", "Main road markets"],
    ["Daneshwari Nagar", "PB Road", "Shakti Nagar"],
    [
      faq("Is AC repair available on Akashavani Road, Dharwad?", "Yes, Hosatti provides doorstep AC repair on Akashavani Road for all brands. Call +91-7899472430."),
      faq("Who does fridge repair on Akashavani Road, Dharwad?", "Our skilled technicians service all fridge brands on Akashavani Road with genuine parts."),
      faq("Is washing machine repair available on Akashavani Road, Dharwad?", "Yes, all washing machine types serviced on Akashavani Road with quick options."),
      faq("Do you repair ACs on Akashavani Road, Dharwad?", "Yes, all AC brands repaired on Akashavani Road — split, window, and inverter units."),
      faq("How do I book service on Akashavani Road, Dharwad?", "Call or WhatsApp +91-7899472430 for doorstep service anywhere on Akashavani Road."),
    ],
  ),
  loc(
    "pb-road-dharwad",
    "PB Road",
    "PB Road (Pune-Bengaluru Highway) is one of Dharwad's busiest and most important roads, with residential areas, institutions, and businesses along its length. Hosatti Refrigeration Service proudly serves all residents and establishments on PB Road, Dharwad for AC repair, refrigerator repair, and all home appliance services. Call for doorstep service anywhere along PB Road or visit our Jay Nagar workshop.",
    ["KSRTC Bus Stand", "District hospital", "PB Road commercial area", "Key junction"],
    ["Court Circle", "Akashavani Road", "Kelgeri Road"],
    [
      faq("Is appliance repair available on PB Road, Dharwad?", "Yes, Hosatti provides complete AC, fridge, and washing machine repair along PB Road, Dharwad."),
      faq("Who does AC repair on PB Road, Dharwad?", "Hosatti Refrigeration Service provides doorstep AC repair anywhere on PB Road for all brands."),
      faq("Is fridge repair available on PB Road, Dharwad?", "Yes, all fridge brands repaired on PB Road with doorstep and workshop options."),
      faq("Do you repair washing machines on PB Road, Dharwad?", "Yes, fully automatic and semi-automatic washing machine repair available on PB Road."),
      faq("Is your workshop accessible from PB Road, Dharwad?", "Yes, our Jay Nagar workshop is easily reached from PB Road. Call +91-7899472430 for directions."),
    ],
  ),
  loc(
    "kelgeri-road-dharwad",
    "Kelgeri Road",
    "Kelgeri Road is a key residential corridor in Dharwad where families depend on Hosatti Refrigeration Service for trustworthy appliance repair. Residents on Kelgeri Road can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Kelgeri Road. Fast, honest appliance repair by Dharwad's most experienced team.",
    ["Kelgeri Lake area", "Kelgeri Road junction", "Residential stretch"],
    ["PB Road", "Haliyal Road", "Barakotri Road"],
    [
      faq("Is AC repair available on Kelgeri Road, Dharwad?", "Yes, doorstep AC repair available on Kelgeri Road for all brands. Call +91-7899472430."),
      faq("Who repairs refrigerators on Kelgeri Road, Dharwad?", "Hosatti Refrigeration Service provides expert fridge repair on Kelgeri Road, Dharwad."),
      faq("Is washing machine repair available on Kelgeri Road, Dharwad?", "Yes, all washing machine types repaired on Kelgeri Road with quick service."),
      faq("Do you provide air cooler repair on Kelgeri Road, Dharwad?", "Yes, all cooler brands serviced on Kelgeri Road — pad, pump, and motor repairs."),
      faq("How do I contact Hosatti for Kelgeri Road, Dharwad?", "Call or WhatsApp +91-7899472430 for doorstep service on Kelgeri Road."),
    ],
  ),
  loc(
    "court-circle-dharwad",
    "Court Circle",
    "Court Circle is a central, bustling area in Dharwad near the district court, surrounded by residential areas that rely on Hosatti Refrigeration Service for all appliance repair needs. Residents near Court Circle, Dharwad can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — conveniently accessible from Court Circle. Expert service for AC, refrigerators, washing machines, and air coolers.",
    ["Dharwad District Court", "Court Circle junction", "Commercial area", "Bus stop"],
    ["PB Road", "Barakotri Road", "Jayanagar"],
    [
      faq("Is AC repair near Court Circle, Dharwad available?", "Yes, Hosatti provides doorstep AC repair near Court Circle for all brands. Call +91-7899472430."),
      faq("Who repairs fridges near Court Circle, Dharwad?", "Our technicians visit homes near Court Circle for all fridge brands and types."),
      faq("Is washing machine repair available near Court Circle, Dharwad?", "Yes, all washing machine types repaired near Court Circle with doorstep service."),
      faq("Do you provide appliance repair in the Court Circle area, Dharwad?", "Yes, we cover all residential areas around Court Circle for AC, fridge, and washing machine repair."),
      faq("How do I reach your workshop from Court Circle, Dharwad?", "Our Jay Nagar workshop is easily accessible from Court Circle. Call +91-7899472430 for directions or home service."),
    ],
  ),
  loc(
    "barakotri-road-dharwad",
    "Barakotri Road",
    "Barakotri Road is a residential stretch in Dharwad with families who trust Hosatti Refrigeration Service for expert appliance repair throughout the year. Residents on Barakotri Road can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Barakotri Road. From AC breakdowns in summer to fridge issues in monsoon, we are always ready.",
    ["Barakotri Road junction", "Local market", "Residential area"],
    ["Court Circle", "Haliyal Road", "PB Road"],
    [
      faq("Is appliance repair available on Barakotri Road, Dharwad?", "Yes, Hosatti provides AC, fridge, washing machine, and cooler repair on Barakotri Road, Dharwad."),
      faq("Who does AC repair on Barakotri Road, Dharwad?", "Hosatti Refrigeration Service provides doorstep AC repair on Barakotri Road for all brands."),
      faq("Is fridge repair available on Barakotri Road, Dharwad?", "Yes, all fridge brands repaired on Barakotri Road with doorstep service."),
      faq("Do you repair washing machines on Barakotri Road, Dharwad?", "Yes, fully automatic and semi-automatic machines repaired on Barakotri Road."),
      faq("How do I contact Hosatti for Barakotri Road service?", "Call or WhatsApp +91-7899472430 for doorstep appliance repair on Barakotri Road, Dharwad."),
    ],
  ),
  loc(
    "haliyal-road-dharwad",
    "Haliyal Road",
    "Haliyal Road is a key road in Dharwad connecting the city to the outskirts, lined with residential communities who depend on Hosatti Refrigeration Service for reliable appliance repair. Residents along Haliyal Road can call our team for doorstep appliance repair at their home, or visit our workshop directly at Jay Nagar, Dharwad — easily accessible from Haliyal Road. We cover all Dharwad areas with professional service and genuine parts.",
    ["Haliyal Road junction", "Residential stretch", "Local shops"],
    ["Kelgeri Road", "Barakotri Road", "KHB Colony"],
    [
      faq("Is AC repair available on Haliyal Road, Dharwad?", "Yes, Hosatti provides doorstep AC repair on Haliyal Road for all brands. Call +91-7899472430."),
      faq("Who repairs refrigerators on Haliyal Road, Dharwad?", "Our technicians visit homes on Haliyal Road for refrigerator repair of all brands."),
      faq("Is washing machine repair available on Haliyal Road, Dharwad?", "Yes, all washing machine types serviced on Haliyal Road with quick options."),
      faq("Do you repair air coolers on Haliyal Road, Dharwad?", "Yes, all cooler brands repaired on Haliyal Road — pads, pumps, and motors."),
      faq("How do I book service on Haliyal Road, Dharwad?", "Call or WhatsApp +91-7899472430 for doorstep appliance repair anywhere on Haliyal Road, Dharwad."),
    ],
  ),
];

export function getLocationBySlug(slug: string): LocationData | undefined {
  return LOCATIONS.find((l) => l.slug === slug);
}
