// src/lib/services.ts
export type ServiceCategory = "ac" | "refrigerator" | "washing-machine" | "air-cooler";

export interface ServiceFAQ { question: string; answer: string; }

export interface ServiceData {
  slug: string;
  name: string;
  category: ServiceCategory;
  categoryLabel: string;
  tagline: string;
  shortDescription: string;
  fullDescription: string;
  symptoms: string[];
  whatIsIncluded: string[];
  brands: string[];
  estimatedTime: string;
  faqs: ServiceFAQ[];
  relatedServices: string[];
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  image: string;
  whatsappMessage: string;
}

export const SERVICES: ServiceData[] = [
  {
    slug: "ac-repair-service-dharwad",
    name: "AC Repair Service",
    category: "ac",
    categoryLabel: "Air Conditioner",
    tagline: "Fast, Reliable AC Repair in Dharwad — All Brands, Same Day",
    shortDescription:
      "Expert AC repair in Dharwad by Hosatti Refrigeration Service. Our skilled technicians diagnose and fix all AC problems — from AC not cooling to PCB faults — with genuine parts and a service warranty.",
    fullDescription:
      "When your AC breaks down in Dharwad's scorching summer heat, you need a trusted technician fast. Hosatti Refrigeration Service has been providing expert AC repair in Dharwad for 15+ years, led by Jameer Hosatti and his team of skilled technicians. We repair all types of ACs — split, window, inverter, and cassette units. Our comprehensive AC repair service covers everything from diagnosing why your AC is not cooling to fixing electrical faults, fan motor failure, thermostat malfunction, PCB board repair, and compressor issues. We service 24+ brands including LG, Samsung, Daikin, Voltas, Blue Star, Carrier, O General, Hitachi, and more. Every repair uses genuine spare parts and is backed by our service warranty. Whether you call us for doorstep AC repair at your home anywhere in Dharwad or bring your unit to our workshop in Jay Nagar — we fix it right the first time.",
    symptoms: [
      "AC not cooling or blowing warm air",
      "AC making loud rattling or grinding noise",
      "AC leaking water inside the room",
      "AC not turning on or no power",
      "AC remote control not working",
      "AC running but room not cooling",
      "AC tripping the circuit breaker",
      "AC making ice on indoor unit",
      "AC smell — musty or burning odor",
      "AC cooling unevenly across the room",
    ],
    whatIsIncluded: [
      "Full AC diagnostic and fault identification",
      "AC PCB (circuit board) repair and replacement",
      "AC compressor repair and testing",
      "Thermostat and sensor repair or replacement",
      "Fan motor (indoor and outdoor) repair",
      "Capacitor and relay replacement",
      "Electrical wiring and connection repair",
      "Drain line cleaning and unclogging",
      "Remote control and receiver repair",
      "Post-repair full system test and performance check",
    ],
    brands: ["LG", "Samsung", "Daikin", "Voltas", "Blue Star", "Carrier", "O General", "Hitachi", "Lloyd", "Mitsubishi", "Panasonic", "Haier", "Godrej"],
    estimatedTime: "1–4 hours depending on the fault",
    faqs: [
      { question: "How much does AC repair cost in Dharwad?", answer: "AC repair cost in Dharwad depends on the exact fault. We provide a transparent upfront quote after diagnosis — no hidden charges. Call +91-7899472430 for a free estimate." },
      { question: "Why is my AC not cooling in Dharwad?", answer: "The most common reasons are: dirty air filter, low refrigerant gas, faulty compressor, blocked condenser coils, or a bad capacitor. Our technicians identify the exact cause and fix it the quick." },
      { question: "How long does AC repair take in Dharwad?", answer: "Most AC repairs take 1–4 hours. Simple faults like capacitor or filter issues are fixed within 1–2 hours. Complex repairs like compressor or PCB replacement may take longer." },
      { question: "Do you repair AC at home in Dharwad?", answer: "Yes! We provide doorstep AC repair service anywhere in Dharwad. Our technician comes to your home. You can also bring your AC unit to our workshop in Jay Nagar, Dharwad." },
      { question: "Which AC brands do you repair in Dharwad?", answer: "We repair all major brands including LG, Samsung, Daikin, Voltas, Blue Star, Carrier, O General, Hitachi, Lloyd, Mitsubishi, Panasonic, Haier, Godrej, and 10+ more brands." },
    ],
    relatedServices: ["ac-gas-refilling-service-dharwad", "ac-deep-cleaning-service-dharwad", "ac-installation-service-dharwad"],
    metaTitle: "AC Repair Service in Dharwad | Hosatti Refrigeration",
    metaDescription: "Expert AC repair in Dharwad by Hosatti Refrigeration Service. All brands. Quick doorstep service. 15+ years experience. Call +91-7899472430 now!",
    keywords: ["AC repair Dharwad", "AC repair service Dharwad", "AC not cooling Dharwad", "AC technician Dharwad", "split AC repair Dharwad", "inverter AC repair Dharwad", "LG AC repair Dharwad", "Samsung AC repair Dharwad", "AC repair near me Dharwad", "quick AC repair Dharwad"],
    image: "/services/AC Not Cooling Repair.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need AC Repair Service in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "ac-gas-refilling-service-dharwad",
    name: "AC Gas Refilling Service",
    category: "ac",
    categoryLabel: "Air Conditioner",
    tagline: "AC Gas Refilling & Leak Repair in Dharwad — All AC Brands",
    shortDescription:
      "Professional AC gas refilling (gas charging) service in Dharwad. We detect refrigerant leaks, repair them, and recharge your AC with the correct gas for full cooling restoration.",
    fullDescription:
      "Is your AC running but not cooling as well as it used to? The problem might be low refrigerant (gas) levels due to a leak. Hosatti Refrigeration Service provides expert AC gas refilling and gas charging in Dharwad. Our technicians first perform a thorough leak detection — because simply topping up the gas without fixing the leak is a temporary fix. Once the leak is sealed, we recharge your AC with the correct refrigerant type (R22, R32, R410A, or R134A) at the precise pressure specified by the manufacturer. The result is restored full cooling power and improved energy efficiency. We service all AC brands and all gas types. Doorstep service anywhere in Dharwad or walk in to our Jay Nagar workshop.",
    symptoms: [
      "AC runs but cooling is weak or insufficient",
      "AC takes very long to cool the room",
      "Ice or frost forming on the copper pipes",
      "AC outdoor unit running continuously",
      "Hissing or bubbling sound from the AC",
      "Increased electricity bill with poor cooling",
    ],
    whatIsIncluded: [
      "AC refrigerant level check and diagnosis",
      "Leak detection using electronic or soap bubble method",
      "Refrigerant leak repair (pipe joints, valve packing)",
      "Gas recharge with correct refrigerant type and quantity",
      "Pressure testing after recharge",
      "Cooling performance verification",
    ],
    brands: ["LG", "Samsung", "Daikin", "Voltas", "Blue Star", "Carrier", "O General", "Hitachi", "Lloyd", "Mitsubishi", "Haier", "Godrej", "Panasonic"],
    estimatedTime: "1–3 hours",
    faqs: [
      { question: "How much does AC gas refilling cost in Dharwad?", answer: "The cost depends on the gas type (R22, R32, R410A) and quantity required. We give a transparent quote upfront. WhatsApp +91-7899472430 for details." },
      { question: "How often does AC gas need to be refilled in Dharwad?", answer: "AC gas does not deplete normally. If your AC needs frequent refilling, you have a refrigerant leak. We detect and fix the leak permanently so you won't need repeated refills." },
      { question: "What gas does my AC use in Dharwad?", answer: "Different AC models use different refrigerants — R22 (older ACs), R32, R410A, or R134A (modern inverter ACs). We carry all types and use only the correct gas for your specific AC model." },
      { question: "Can AC run without gas in Dharwad?", answer: "An AC with zero or very low refrigerant will run but produce little to no cooling. Running it in this state can damage the compressor. Get it recharged immediately by calling +91-7899472430." },
      { question: "Do you provide AC gas refilling at home in Dharwad?", answer: "Yes, we provide doorstep AC gas refilling service anywhere in Dharwad. Our technician brings all necessary equipment to your home for a complete on-site service." },
    ],
    relatedServices: ["ac-repair-service-dharwad", "ac-deep-cleaning-service-dharwad", "ac-installation-service-dharwad"],
    metaTitle: "AC Gas Refilling Service Dharwad | Hosatti Refrigeration",
    metaDescription: "AC gas refilling & leak repair in Dharwad. All refrigerant types — R22, R32, R410A. Doorstep service, all brands. Call +91-7899472430 today!",
    keywords: ["AC gas refilling Dharwad", "AC gas charging Dharwad", "AC refrigerant recharge Dharwad", "AC gas filling Dharwad", "R22 gas refilling Dharwad", "R32 gas refilling Dharwad", "AC gas leak repair Dharwad", "AC cooling problem Dharwad"],
    image: "/services/AC Gas Refilling  Gas Charging.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need AC Gas Refilling Service in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "ac-deep-cleaning-service-dharwad",
    name: "AC Deep Cleaning Service",
    category: "ac",
    categoryLabel: "Air Conditioner",
    tagline: "Professional AC Deep Cleaning in Dharwad — Restore Performance & Air Quality",
    shortDescription:
      "Complete AC deep cleaning service in Dharwad. We clean indoor coils, blower fans, filters, drain pans, and outdoor units to improve cooling efficiency, air quality, and AC lifespan.",
    fullDescription:
      "Dharwad's dusty summers clog your AC filters and coils faster than you might think. A dirty AC doesn't just cool poorly — it also circulates dust, mold spores, and bacteria into your home air. Hosatti Refrigeration Service provides thorough AC deep cleaning in Dharwad, covering every internal component: the evaporator coil, blower fan wheel, air filter, drain pan and drain line, outdoor condenser coil, and outer unit body. After our deep cleaning, your AC runs more efficiently — often feeling like a new unit — and your electricity bill can visibly reduce due to better airflow. We recommend annual deep cleaning before summer and additional service during monsoon if mold is suspected. Doorstep service anywhere in Dharwad.",
    symptoms: [
      "AC not cooling as effectively as before",
      "Bad or musty smell from the AC",
      "Weak airflow from indoor unit",
      "Visible dust or mold on AC vents",
      "AC making more noise than usual",
      "Increased electricity consumption",
    ],
    whatIsIncluded: [
      "Air filter removal, washing, and reinstallation",
      "Evaporator (indoor) coil cleaning with foam jet wash",
      "Blower fan wheel deep cleaning",
      "Drain pan cleaning and sanitizing",
      "Drain line flushing to clear blockages",
      "Outdoor condenser coil cleaning",
      "Outer body and vents wiping",
      "Post-cleaning cooling efficiency check",
    ],
    brands: ["LG", "Samsung", "Daikin", "Voltas", "Blue Star", "Carrier", "O General", "Hitachi", "Lloyd", "Mitsubishi", "Haier", "Godrej", "Panasonic", "Whirlpool"],
    estimatedTime: "1–2 hours per unit",
    faqs: [
      { question: "How often should I get AC deep cleaning in Dharwad?", answer: "We recommend AC deep cleaning at least once a year — ideally before the summer season begins (February–March). If you use your AC heavily or notice reduced cooling or bad smell, clean it more frequently." },
      { question: "Is AC deep cleaning different from regular servicing in Dharwad?", answer: "Yes. Regular servicing typically covers filter cleaning only. Deep cleaning is a comprehensive internal clean of coils, blower fan, drain pan, and outdoor unit — not just the filter. It's far more thorough." },
      { question: "Can AC deep cleaning fix poor cooling in Dharwad?", answer: "In many cases, yes! Clogged coils and dirty filters significantly reduce cooling output. After a proper deep clean, most customers notice immediate improvement in cooling and airflow." },
      { question: "Does AC deep cleaning take a long time in Dharwad?", answer: "Each AC unit takes 1–2 hours for a thorough deep clean. Multiple units in the same home can be done in one visit for efficiency." },
      { question: "Do you carry cleaning equipment to my home in Dharwad?", answer: "Yes, our technicians bring all professional cleaning equipment — jet wash machine, cleaning chemicals, protective sheets — for complete doorstep AC deep cleaning anywhere in Dharwad." },
    ],
    relatedServices: ["ac-repair-service-dharwad", "ac-gas-refilling-service-dharwad", "ac-installation-service-dharwad"],
    metaTitle: "AC Deep Cleaning Service Dharwad | Hosatti Refrigeration",
    metaDescription: "Professional AC deep cleaning in Dharwad. Coil, filter, blower & drain cleaning. Improves cooling & air quality. Call +91-7899472430 for doorstep service!",
    keywords: ["AC deep cleaning Dharwad", "AC cleaning service Dharwad", "AC servicing Dharwad", "AC coil cleaning Dharwad", "AC filter cleaning Dharwad", "AC maintenance Dharwad", "AC smell removal Dharwad"],
    image: "/services/AC Deep Cleaning Service.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need AC Deep Cleaning Service in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "ac-installation-service-dharwad",
    name: "AC Installation & Uninstallation Service",
    category: "ac",
    categoryLabel: "Air Conditioner",
    tagline: "Expert AC Installation & Uninstallation in Dharwad — All AC Brands",
    shortDescription:
      "Professional AC installation and uninstallation service in Dharwad. We install split ACs, window ACs, and inverter ACs with precise pipe fitting, electrical connections, and performance testing.",
    fullDescription:
      "Proper AC installation is the foundation of efficient, long-lasting performance. An incorrectly installed AC leaks refrigerant, drains poorly, and wears out faster. Hosatti Refrigeration Service provides expert AC installation in Dharwad for all types — split ACs, window ACs, cassette ACs, and inverter models. Our skilled technicians handle the entire process: mounting the indoor unit at the optimal position, drilling and routing copper pipes, installing the outdoor unit on a sturdy bracket, making all electrical connections correctly, and performing a full refrigerant pressure check and cooling test before leaving. We also uninstall ACs safely when you're relocating or replacing units, ensuring no refrigerant is wasted and your walls are minimally impacted.",
    symptoms: [
      "New AC purchase requiring installation",
      "Relocating home and need to move AC",
      "Old AC needs to be uninstalled for replacement",
      "AC not working after previous incorrect installation",
      "AC leaking because drainage was set up incorrectly",
    ],
    whatIsIncluded: [
      "Indoor unit wall mounting with brackets",
      "Outdoor unit bracket installation and securing",
      "Copper pipe routing and insulation",
      "Drain pipe installation with proper slope for drainage",
      "Electrical connection and MCB setup",
      "Refrigerant pressure check and system testing",
      "Full cooling performance test",
      "Safe AC uninstallation with refrigerant recovery",
    ],
    brands: ["LG", "Samsung", "Daikin", "Voltas", "Blue Star", "Carrier", "O General", "Hitachi", "Lloyd", "Mitsubishi", "Haier", "Panasonic", "Godrej"],
    estimatedTime: "2–4 hours for installation",
    faqs: [
      { question: "How much does AC installation cost in Dharwad?", answer: "AC installation cost depends on the AC type (split vs window), wall type, pipe length required, and electrical work needed. We provide a transparent quote. Call +91-7899472430 for details." },
      { question: "Can you install any brand of AC in Dharwad?", answer: "Yes, we install all major AC brands in Dharwad including LG, Samsung, Daikin, Voltas, Blue Star, Carrier, O General, Hitachi, Lloyd, Mitsubishi, Haier, and more." },
      { question: "How long does AC installation take in Dharwad?", answer: "A standard split AC installation takes 2–4 hours. This includes wall mounting, pipe routing, electrical connections, and final testing. Complex installations may take longer." },
      { question: "Do I need to buy any materials before AC installation in Dharwad?", answer: "We bring all standard materials needed — copper pipes, drain pipe, insulation tape, and fixings. Any extra pipe length or specialty materials may involve additional cost which we quote upfront." },
      { question: "Do you also uninstall AC for relocation in Dharwad?", answer: "Yes, we safely uninstall ACs for home relocation or unit replacement. We recover the refrigerant properly and minimize wall damage during the process." },
    ],
    relatedServices: ["ac-repair-service-dharwad", "ac-gas-refilling-service-dharwad", "ac-deep-cleaning-service-dharwad"],
    metaTitle: "AC Installation Service Dharwad | Hosatti Refrigeration",
    metaDescription: "Expert AC installation & uninstallation in Dharwad. Split, window & inverter ACs. All brands. Professional fitting & testing. Call +91-7899472430 today!",
    keywords: ["AC installation Dharwad", "AC fitting Dharwad", "split AC installation Dharwad", "inverter AC installation Dharwad", "AC uninstallation Dharwad", "new AC installation Dharwad", "AC relocation Dharwad"],
    image: "/services/AC Not Cooling Repair.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need AC Installation Service in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "refrigerator-repair-service-dharwad",
    name: "Refrigerator Not Cooling Repair",
    category: "refrigerator",
    categoryLabel: "Refrigerator",
    tagline: "Fast Fridge Repair in Dharwad — Refrigerator Not Cooling Fixed Same Day",
    shortDescription:
      "Expert refrigerator not cooling repair in Dharwad by Hosatti Refrigeration Service. We diagnose and fix all fridge cooling problems — compressor, thermostat, gas leaks, and more — with genuine parts.",
    fullDescription:
      "A refrigerator that stops cooling is an emergency — food spoils fast in Dharwad's warm climate. Hosatti Refrigeration Service provides fast, reliable refrigerator repair in Dharwad, with 15+ years of experience fixing all cooling problems. Our technicians diagnose the true root cause before starting repairs: dirty condenser coils reducing heat dissipation, faulty thermostat not signaling the compressor, refrigerant leak causing loss of cooling capacity, blocked defrost drain causing ice buildup, or a worn door seal letting warm air in. We fix all these issues with genuine replacement parts for lasting results. Single-door, double-door, French door, and side-by-side refrigerators are all within our expertise. Call for doorstep fridge repair anywhere in Dharwad, or bring your appliance to our Jay Nagar workshop.",
    symptoms: [
      "Fridge not cooling or barely cool inside",
      "Fridge compressor running continuously",
      "Food spoiling faster than usual",
      "Freezer working but fridge section warm",
      "Fridge making loud humming or ticking noise",
      "Fridge not cooling after a power cut",
      "Water leaking from inside the fridge",
      "Ice buildup on fridge walls or freezer",
    ],
    whatIsIncluded: [
      "Full refrigerator diagnosis and fault identification",
      "Thermostat testing and replacement",
      "Condenser coil cleaning and inspection",
      "Door gasket inspection and replacement",
      "Evaporator fan motor repair or replacement",
      "Defrost heater and timer repair",
      "Start relay and overload protector replacement",
      "PCB and control board repair",
      "Temperature sensor testing and replacement",
    ],
    brands: ["LG", "Samsung", "Godrej", "Whirlpool", "Haier", "Bosch", "Siemens", "Electrolux", "Videocon", "Panasonic", "Hitachi", "Sharp", "Onida", "BPL", "Kelvinator"],
    estimatedTime: "1–3 hours for most repairs",
    faqs: [
      { question: "Why is my refrigerator not cooling in Dharwad?", answer: "Common causes include faulty thermostat, dirty condenser coils, refrigerant leak, broken compressor start relay, defective evaporator fan, or a worn door seal. Our technicians diagnose and fix the exact cause." },
      { question: "How much does fridge repair cost in Dharwad?", answer: "Fridge repair cost varies by fault type and brand. We provide transparent quotes before starting any work. Call or WhatsApp +91-7899472430 for a free estimate." },
      { question: "Can a fridge be repaired at home in Dharwad?", answer: "Yes, our technicians provide doorstep refrigerator repair service anywhere in Dharwad. We carry common spare parts to fix most faults in one visit." },
      { question: "How long does refrigerator repair take in Dharwad?", answer: "Most fridge repairs take 1–3 hours on-site. Complex repairs like compressor replacement may require the appliance to be brought to our workshop for 1–2 days." },
      { question: "My fridge stopped cooling after a power cut in Dharwad. What should I do?", answer: "Unplug the fridge for 5–10 minutes then plug it back in. If it still doesn't cool after a few hours, call us at +91-7899472430. Power surges can damage the compressor start relay or PCB." },
    ],
    relatedServices: ["fridge-compressor-repair-dharwad", "refrigerator-gas-recharge-dharwad", "washing-machine-repair-service-dharwad"],
    metaTitle: "Refrigerator Repair Service Dharwad | Hosatti Refrigeration",
    metaDescription: "Expert refrigerator not cooling repair in Dharwad. All brands, quick doorstep service. 15+ years experience. Genuine parts. Call +91-7899472430 now!",
    keywords: ["refrigerator repair Dharwad", "fridge repair Dharwad", "fridge not cooling Dharwad", "refrigerator not cooling Dharwad", "fridge repair service Dharwad", "LG fridge repair Dharwad", "Samsung fridge repair Dharwad", "Godrej fridge repair Dharwad"],
    image: "/services/Refrigerator Not Cooling Repair.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need Refrigerator Repair in Dharwad — my fridge is not cooling.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "fridge-compressor-repair-dharwad",
    name: "Fridge Compressor Repair & Replacement",
    category: "refrigerator",
    categoryLabel: "Refrigerator",
    tagline: "Expert Fridge Compressor Repair in Dharwad — All Brands, Genuine Parts",
    shortDescription:
      "Specialist fridge compressor repair and replacement in Dharwad. Our certified technicians diagnose compressor failure accurately and replace using genuine compressors with warranty.",
    fullDescription:
      "The compressor is the heart of your refrigerator — and when it fails, the fridge stops cooling entirely. Hosatti Refrigeration Service specializes in fridge compressor repair and replacement in Dharwad for all brands. Our technicians first confirm compressor failure using proper electrical testing (not just guesswork), because a faulty start relay often mimics a dead compressor — and replacing a start relay is far less expensive. If the compressor itself has failed, we replace it with a genuine OEM-compatible compressor matched to your refrigerator model. After replacement, we also recharge the refrigerant and perform a complete leak test and cooling verification. We service single-door, double-door, and frost-free refrigerators from LG, Samsung, Godrej, Whirlpool, Haier, Bosch, and all other brands.",
    symptoms: [
      "Fridge completely warm — not cooling at all",
      "Compressor not starting when you plug in the fridge",
      "Compressor starting and immediately stopping",
      "Clicking sound from the back of the fridge (relay failure)",
      "Fridge running hot at the back but not cooling inside",
      "Compressor running continuously without cooling",
    ],
    whatIsIncluded: [
      "Compressor electrical testing and diagnosis",
      "Start relay and overload protector testing",
      "Genuine compressor replacement (if required)",
      "Refrigerant recovery and recharge post-replacement",
      "Leak test after compressor installation",
      "Full cooling performance test",
      "Service warranty on compressor replacement",
    ],
    brands: ["LG", "Samsung", "Godrej", "Whirlpool", "Haier", "Bosch", "Siemens", "Electrolux", "Videocon", "Panasonic", "Hitachi", "Onida", "BPL", "Kelvinator"],
    estimatedTime: "Quick diagnosis; replacement typically 1 day",
    faqs: [
      { question: "How do I know if my fridge compressor has failed in Dharwad?", answer: "Signs of compressor failure: fridge not cooling at all, compressor not starting, clicking sound from the back, or compressor running but not cooling. Our technicians run an electrical test to confirm." },
      { question: "How much does fridge compressor replacement cost in Dharwad?", answer: "Cost varies by refrigerator brand, model, and compressor type. We provide a transparent quote after diagnosis. We never replace a compressor without confirming it's truly faulty." },
      { question: "Is it worth repairing a fridge compressor in Dharwad?", answer: "It depends on the fridge's age and model. For fridges under 8–10 years old in good condition, compressor replacement is generally worth it. Our technicians advise honestly based on your specific situation." },
      { question: "How long does fridge compressor replacement take in Dharwad?", answer: "Compressor replacement typically requires the fridge to be at our workshop for 1 day. We diagnose on the spot and schedule the replacement promptly." },
      { question: "Do you provide warranty on compressor replacement in Dharwad?", answer: "Yes, we provide warranty on compressor replacement. The warranty period covers both the part and our workmanship. Ask our technician for specific terms at the time of service." },
    ],
    relatedServices: ["refrigerator-repair-service-dharwad", "refrigerator-gas-recharge-dharwad", "ac-repair-service-dharwad"],
    metaTitle: "Fridge Compressor Repair Dharwad | Hosatti Refrigeration",
    metaDescription: "Expert fridge compressor repair & replacement in Dharwad. Genuine parts, warranty. All brands. Call +91-7899472430 — quick diagnosis!",
    keywords: ["fridge compressor repair Dharwad", "fridge compressor replacement Dharwad", "refrigerator compressor repair Dharwad", "compressor not working Dharwad", "fridge not cooling compressor Dharwad"],
    image: "/services/Fridge Compressor Repair & Replacement.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need Fridge Compressor Repair in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "refrigerator-gas-recharge-dharwad",
    name: "Refrigerator Gas Filling / Gas Recharge",
    category: "refrigerator",
    categoryLabel: "Refrigerator",
    tagline: "Refrigerator Gas Filling & Leak Repair in Dharwad — Restore Full Cooling",
    shortDescription:
      "Expert refrigerator gas filling and recharge service in Dharwad. We detect refrigerant leaks, repair them, and recharge your fridge with the correct gas for optimal cooling restoration.",
    fullDescription:
      "If your refrigerator is cooling less effectively than it used to, or if the freezer works but the fridge section stays warm, the culprit may be low refrigerant (gas) due to a leak. Hosatti Refrigeration Service provides precision refrigerator gas filling and recharge in Dharwad. Our approach is thorough: we identify and repair the leak source first — joints, valve stems, capillary tubes — then recharge with the exact gas type (R134A, R600A, or R22 for older models) at the manufacturer-specified pressure. Skipping the leak repair and just topping up the gas is a short-term fix — we do it right the first time. After recharge, we verify the temperature drop to confirm complete restoration. All brands and all refrigerator types serviced in Dharwad.",
    symptoms: [
      "Fridge running but not cold enough",
      "Freezer icing but fridge section warm",
      "Fridge takes very long to get cold",
      "Fridge running day and night without proper cooling",
      "Ice forming on copper pipes inside the freezer",
    ],
    whatIsIncluded: [
      "Refrigerant level diagnosis",
      "Leak detection and location identification",
      "Leak repair (pipe joints, valve stems, evaporator)",
      "Gas recharge with correct refrigerant at correct pressure",
      "Post-recharge leak test",
      "Temperature verification across fridge compartments",
    ],
    brands: ["LG", "Samsung", "Godrej", "Whirlpool", "Haier", "Bosch", "Videocon", "Panasonic", "Hitachi", "Onida", "BPL", "Kelvinator", "TCL"],
    estimatedTime: "2–4 hours",
    faqs: [
      { question: "How much does fridge gas refilling cost in Dharwad?", answer: "Cost depends on gas type and quantity. Older fridges use R22 or R134A; newer models use R600A. We quote transparently before starting. Call +91-7899472430 for details." },
      { question: "Why does my fridge keep losing gas in Dharwad?", answer: "Fridge gas doesn't deplete on its own. If your fridge repeatedly needs gas, you have a leak that must be repaired. We find the exact leak point and fix it permanently." },
      { question: "Can refrigerator gas refilling be done at home in Dharwad?", answer: "Yes, our technicians carry gas cylinders and charging equipment for doorstep service anywhere in Dharwad." },
      { question: "How long after gas refilling will my fridge cool properly in Dharwad?", answer: "After proper recharge, your fridge typically reaches its operating temperature within 2–4 hours. We verify cooling before leaving your home." },
      { question: "Is refrigerator gas filling safe to do at home in Dharwad?", answer: "Refrigerant handling requires professional equipment and certification. Our trained technicians handle it safely. Never attempt DIY gas refilling." },
    ],
    relatedServices: ["refrigerator-repair-service-dharwad", "fridge-compressor-repair-dharwad", "ac-gas-refilling-service-dharwad"],
    metaTitle: "Refrigerator Gas Filling Dharwad | Hosatti Refrigeration",
    metaDescription: "Refrigerator gas filling & recharge in Dharwad. Leak detection & repair, all gas types, all brands. Call +91-7899472430 for fast doorstep service!",
    keywords: ["refrigerator gas filling Dharwad", "fridge gas recharge Dharwad", "fridge gas filling Dharwad", "refrigerator gas refilling Dharwad", "R134A gas filling Dharwad", "refrigerant leak repair Dharwad"],
    image: "/services/Refrigerator Gas Filling  Gas Recharge.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need Refrigerator Gas Filling in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "washing-machine-repair-service-dharwad",
    name: "Washing Machine Not Draining Repair",
    category: "washing-machine",
    categoryLabel: "Washing Machine",
    tagline: "Washing Machine Not Draining? Fast Fix in Dharwad — All Brands",
    shortDescription:
      "Expert washing machine not draining repair in Dharwad. We clear clogged drain pumps, fix drain hose blockages, and repair pump motors for all fully automatic and semi-automatic washing machine brands.",
    fullDescription:
      "A washing machine that won't drain leaves clothes soaking in dirty water and halts your laundry completely. Hosatti Refrigeration Service provides fast, effective washing machine not draining repair in Dharwad for all brands and types. Our technicians diagnose the root cause accurately: a clogged drain pump filter packed with lint and debris, a kinked or blocked drain hose, a faulty drain pump motor, a stuck lid switch (in top-load machines), or an electronic control board fault. We clear blockages, replace faulty pumps, and repair wiring faults — ensuring your washing machine drains completely after every cycle. We service LG, Samsung, IFB, Whirlpool, Bosch, Godrej, Videocon, and all other brands. Doorstep service throughout Dharwad or walk-in to our Jay Nagar workshop.",
    symptoms: [
      "Water stays in the tub after the wash cycle ends",
      "Clothes come out soaking wet",
      "Washing machine stops mid-cycle with water inside",
      "Error code on washing machine display (drain error)",
      "Buzzing sound during drain cycle but water doesn't empty",
      "Drain hose not releasing water properly",
    ],
    whatIsIncluded: [
      "Drain pump filter cleaning and clearing",
      "Drain hose inspection and clearing",
      "Drain pump motor testing and replacement",
      "Lid switch and door latch inspection",
      "Control board drain circuit testing",
      "Drain pipe routing correction",
      "Post-repair test drain cycle",
    ],
    brands: ["LG", "Samsung", "IFB", "Whirlpool", "Bosch", "Godrej", "Videocon", "Haier", "Panasonic", "Siemens", "Electrolux", "Onida"],
    estimatedTime: "1–3 hours",
    faqs: [
      { question: "Why is my washing machine not draining water in Dharwad?", answer: "The most common cause is a clogged drain pump filter blocked with lint, coins, or debris. Other causes include a kinked drain hose, faulty drain pump motor, or electronic control board issue." },
      { question: "Can I fix a washing machine drain problem myself in Dharwad?", answer: "You can try cleaning the drain pump filter (usually accessible via a front hatch) yourself. If that doesn't fix it, call us — the pump motor or control board may need professional repair." },
      { question: "How much does washing machine drain repair cost in Dharwad?", answer: "It depends on the fault. Filter cleaning is the simplest and most affordable fix. Pump motor replacement costs more. We quote transparently before starting any work." },
      { question: "Do you repair all washing machine brands for drain issues in Dharwad?", answer: "Yes — we repair drain problems in LG, Samsung, IFB, Whirlpool, Bosch, Godrej, Videocon, Haier, Panasonic, Siemens, and all other brands in Dharwad." },
      { question: "How long does washing machine drain repair take in Dharwad?", answer: "Most drain repairs are completed in 1–3 hours during a single doorstep visit. Pump motor replacement may take slightly longer but is usually done the quick." },
    ],
    relatedServices: ["fully-automatic-washing-machine-repair-dharwad", "semi-automatic-washing-machine-repair-dharwad", "refrigerator-repair-service-dharwad"],
    metaTitle: "Washing Machine Not Draining Repair Dharwad | Hosatti",
    metaDescription: "Washing machine not draining repair in Dharwad. Drain pump fix, all brands, quick doorstep service. Call +91-7899472430 — Hosatti Refrigeration!",
    keywords: ["washing machine not draining Dharwad", "washing machine drain repair Dharwad", "washing machine not draining water Dharwad", "drain pump repair Dharwad", "washing machine repair Dharwad"],
    image: "/services/Washing Machine Not Draining Repair.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nMy washing machine is not draining. I need repair in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "fully-automatic-washing-machine-repair-dharwad",
    name: "Fully Automatic Washing Machine Repair",
    category: "washing-machine",
    categoryLabel: "Washing Machine",
    tagline: "Expert Fully Automatic Washing Machine Repair in Dharwad — Top & Front Load",
    shortDescription:
      "Complete fully automatic washing machine repair in Dharwad for top-load and front-load machines. PCB faults, drum issues, motor failure, door lock problems — all fixed with genuine parts.",
    fullDescription:
      "Fully automatic washing machines are sophisticated appliances with electronic controls, sensors, and multiple wash programs. When they malfunction, you need a technician who understands both the mechanical and electronic systems. Hosatti Refrigeration Service provides comprehensive fully automatic washing machine repair in Dharwad for all brands — LG, Samsung, IFB, Whirlpool, Bosch, Siemens, Godrej, Haier, and more. We repair top-load fully automatic and front-load fully automatic machines. Common issues we fix include drum not rotating, PCB control board faults, motor failure, door lock mechanism failure, inlet valve problems, drain issues, vibration and noise during spin, water not filling, and error code diagnosis and reset. Our technicians carry common spare parts for quick repair wherever possible.",
    symptoms: [
      "Drum not rotating during wash or spin",
      "Washing machine showing error codes",
      "Door not opening or door lock failure",
      "Machine not filling water",
      "Excessive vibration and noise during spin",
      "Washing machine stopping mid-cycle",
      "Clothes not getting properly clean",
      "Water not draining after wash",
    ],
    whatIsIncluded: [
      "Full diagnostic including error code reading",
      "PCB (control board) repair and replacement",
      "Drum bearing and spider arm repair",
      "Wash and drain motor repair or replacement",
      "Door lock mechanism repair or replacement",
      "Water inlet valve repair or replacement",
      "Shock absorber and spring replacement",
      "Belt and pulley system inspection",
      "Pressure switch and sensor testing",
    ],
    brands: ["LG", "Samsung", "IFB", "Whirlpool", "Bosch", "Siemens", "Godrej", "Haier", "Panasonic", "Electrolux", "Videocon"],
    estimatedTime: "1–4 hours",
    faqs: [
      { question: "Who repairs fully automatic washing machines in Dharwad?", answer: "Hosatti Refrigeration Service specializes in fully automatic washing machine repair in Dharwad — both top-load and front-load machines. Call +91-7899472430 for quick service." },
      { question: "Why is my fully automatic washing machine showing an error code in Dharwad?", answer: "Error codes indicate specific faults — drain errors (clogged pump), door errors (lock failure), water supply errors (inlet valve), or motor faults. We read and diagnose error codes precisely." },
      { question: "Can fully automatic washing machine drum bearings be replaced in Dharwad?", answer: "Yes, we replace drum bearings for all fully automatic washing machine brands in Dharwad. Bearing replacement involves drum disassembly but significantly extends the machine's life." },
      { question: "How much does fully automatic washing machine repair cost in Dharwad?", answer: "Repair cost depends on the fault — simple repairs like door latch or shock absorber replacement are standard; PCB or motor replacement costs more. We provide transparent quotes before starting." },
      { question: "Do you repair IFB and Bosch washing machines in Dharwad?", answer: "Yes, we service IFB, Bosch, and all other premium brands of fully automatic washing machines in Dharwad with genuine or OEM-compatible spare parts." },
    ],
    relatedServices: ["semi-automatic-washing-machine-repair-dharwad", "washing-machine-repair-service-dharwad", "refrigerator-repair-service-dharwad"],
    metaTitle: "Fully Automatic Washing Machine Repair Dharwad | Hosatti",
    metaDescription: "Fully automatic washing machine repair in Dharwad — top & front load. LG, Samsung, IFB, Bosch & more. Quick doorstep fix. Call +91-7899472430!",
    keywords: ["fully automatic washing machine repair Dharwad", "front load washing machine repair Dharwad", "top load washing machine repair Dharwad", "IFB washing machine repair Dharwad", "LG washing machine repair Dharwad", "washing machine PCB repair Dharwad"],
    image: "/services/Fully Automatic Washing Machine Repai.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need Fully Automatic Washing Machine Repair in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "semi-automatic-washing-machine-repair-dharwad",
    name: "Semi-Automatic Washing Machine Repair",
    category: "washing-machine",
    categoryLabel: "Washing Machine",
    tagline: "Semi-Automatic Washing Machine Repair in Dharwad — All Brands, Fast Fix",
    shortDescription:
      "Reliable semi-automatic washing machine repair in Dharwad. Spinner not working, pulsator failure, timer issues, pump blockages — we fix all faults in all brands, quick.",
    fullDescription:
      "Semi-automatic washing machines remain widely used across Dharwad households for their simplicity, water efficiency, and long-lasting build. Hosatti Refrigeration Service provides complete semi-automatic washing machine repair in Dharwad for all brands. Common problems we repair include the spinner not working or spinning slowly, pulsator not rotating (wash tub motor failure), timer not advancing through cycles, water pump not draining the wash tub, lid switch faults, noisy operation due to worn bearings, and belt replacement. We stock common spare parts for semi-automatic machines including motors, timers, pumps, and belts, enabling quick repairs in most cases. Doorstep service anywhere in Dharwad or walk-in to our workshop at Jay Nagar.",
    symptoms: [
      "Spinner not working or spinning slowly",
      "Wash tub motor not rotating (pulsator failure)",
      "Timer not advancing or stopping mid-cycle",
      "Water not draining from the wash tub",
      "Loud noise or vibration during spin",
      "Machine not starting when switched on",
      "Lid switch not working",
    ],
    whatIsIncluded: [
      "Full semi-automatic machine diagnostic",
      "Wash motor and spin motor testing and replacement",
      "Pulsator repair or replacement",
      "Timer and selector switch repair",
      "Drain pump cleaning and replacement",
      "Drive belt inspection and replacement",
      "Lid switch and safety mechanism repair",
      "Bearing inspection and replacement",
    ],
    brands: ["LG", "Samsung", "Godrej", "Whirlpool", "Videocon", "Haier", "Onida", "BPL", "Kelvinator", "TCL"],
    estimatedTime: "1–3 hours",
    faqs: [
      { question: "Why is my semi-automatic washing machine spinner not working in Dharwad?", answer: "The spinner (spin motor) may have failed, the drive belt may be broken, or the lid switch may be faulty preventing the spin cycle from starting. Our technicians diagnose accurately and fix it the quick." },
      { question: "How much does semi-automatic washing machine repair cost in Dharwad?", answer: "Repair cost depends on the part that needs replacement — belts and pumps are affordable; motor replacement costs more. We quote transparently before starting any work." },
      { question: "Can you repair old semi-automatic washing machines in Dharwad?", answer: "Yes, we repair all ages of semi-automatic washing machines. Many older models like Godrej, BPL, Kelvinator are very repairable and worth maintaining. Spare parts are generally available." },
      { question: "My semi-automatic machine is making a loud noise during spin in Dharwad. What's wrong?", answer: "Loud noise during spin is usually caused by worn spin bearing, unbalanced load, or a damaged spin basket. Our technicians identify and fix the cause quickly." },
      { question: "Do you repair Videocon and Onida semi-automatic washing machines in Dharwad?", answer: "Yes, we service all brands of semi-automatic washing machines in Dharwad including Videocon, Onida, BPL, and Kelvinator alongside more popular brands." },
    ],
    relatedServices: ["fully-automatic-washing-machine-repair-dharwad", "washing-machine-repair-service-dharwad", "air-cooler-repair-service-dharwad"],
    metaTitle: "Semi-Automatic Washing Machine Repair Dharwad | Hosatti",
    metaDescription: "Semi-automatic washing machine repair in Dharwad. Spinner, pulsator, timer & pump fixes. All brands, quick doorstep service. Call +91-7899472430!",
    keywords: ["semi automatic washing machine repair Dharwad", "semi-automatic washing machine repair Dharwad", "spinner repair Dharwad", "pulsator repair Dharwad", "washing machine motor repair Dharwad"],
    image: "/services/Semi-Automatic Washing Machine Repair.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need Semi-Automatic Washing Machine Repair in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "air-cooler-repair-service-dharwad",
    name: "Air Cooler Not Cooling Repair",
    category: "air-cooler",
    categoryLabel: "Air Cooler",
    tagline: "Air Cooler Not Cooling in Dharwad? Fast Fix by Expert Technicians",
    shortDescription:
      "Expert air cooler not cooling repair in Dharwad. Cooling pad replacement, water pump repair, motor issues, and fan blade problems — all fixed with genuine parts and warranty.",
    fullDescription:
      "Air coolers are essential companions through Dharwad's long, hot summers. When your cooler blows warm air or barely cools, something has gone wrong with its evaporative system. Hosatti Refrigeration Service provides fast air cooler not cooling repair in Dharwad for all brands — Symphony, Bajaj, Crompton, Orient, Kenstar, Havells, and more. The most common causes of poor cooling are dry or heavily soiled cooling pads that no longer evaporate water effectively, a faulty water pump not circulating water to the pads, clogged or broken water distribution nozzles, and a weak or failed fan motor not generating sufficient airflow. We diagnose and fix all these issues with quality replacement parts. Doorstep service anywhere in Dharwad.",
    symptoms: [
      "Air cooler running but blowing warm or slightly cool air",
      "Cooler pads are dry even when water tank is full",
      "Water pump sound but water not reaching pads",
      "Weak airflow from the cooler",
      "Cooler making gurgling sound but not cooling",
      "Water leaking from the cooler",
    ],
    whatIsIncluded: [
      "Cooling pad inspection and replacement",
      "Water pump testing and replacement",
      "Water distribution nozzle cleaning or replacement",
      "Fan blade inspection and balancing",
      "Water tank cleaning and inspection",
      "Float valve inspection and adjustment",
      "Post-repair cooling performance test",
    ],
    brands: ["Symphony", "Bajaj", "Crompton", "Orient", "Kenstar", "Havells", "Usha", "Voltas", "Cello", "Maharaja Whiteline"],
    estimatedTime: "1–2 hours",
    faqs: [
      { question: "Why is my air cooler not cooling in Dharwad summers?", answer: "The most common causes are: dry or dirty cooling pads, faulty water pump not circulating water, clogged nozzles, or a weak fan motor. Our technicians identify and fix the exact problem." },
      { question: "How often should cooling pads be replaced in Dharwad?", answer: "Cooling pads typically last 1–2 seasons. Dharwad's hard water causes mineral deposits on pads over time, reducing efficiency. We assess pad condition and replace them if necessary." },
      { question: "Can air cooler repair be done at home in Dharwad?", answer: "Yes, our technicians provide doorstep air cooler repair service anywhere in Dharwad. Most repairs — including pad replacement and pump repair — are done on-site." },
      { question: "My air cooler has water but pads are dry. What's wrong in Dharwad?", answer: "This is a water pump or nozzle fault. The pump may have failed, or the distribution nozzles are clogged with mineral deposits from hard water. We clean or replace the pump and nozzles." },
      { question: "How much does air cooler repair cost in Dharwad?", answer: "Cost depends on the part — pad replacement and nozzle cleaning are affordable; pump or motor replacement costs more. We provide a transparent quote before starting. Call +91-7899472430." },
    ],
    relatedServices: ["air-cooler-motor-repair-dharwad", "ac-repair-service-dharwad", "ac-deep-cleaning-service-dharwad"],
    metaTitle: "Air Cooler Repair Service Dharwad | Hosatti Refrigeration",
    metaDescription: "Air cooler not cooling repair in Dharwad. Pad replacement, pump repair, fan fixes. All brands, quick service. Call +91-7899472430 — Hosatti!",
    keywords: ["air cooler repair Dharwad", "air cooler not cooling Dharwad", "cooler repair Dharwad", "air cooler service Dharwad", "cooler pump repair Dharwad", "cooling pad replacement Dharwad"],
    image: "/services/Air Cooler Not Cooling Repair.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nMy air cooler is not cooling. I need repair in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
  {
    slug: "air-cooler-motor-repair-dharwad",
    name: "Air Cooler Motor Repair & Replacement",
    category: "air-cooler",
    categoryLabel: "Air Cooler",
    tagline: "Air Cooler Motor Repair & Replacement in Dharwad — Genuine Parts, Warranty",
    shortDescription:
      "Specialist air cooler motor repair and replacement in Dharwad. Fan motor burnout, bearing failure, capacitor fault, and motor rewinding — all done with genuine parts and service warranty.",
    fullDescription:
      "The fan motor is the core of your air cooler's performance. A failing or burnt motor means little to no airflow — and no airflow means no cooling. Hosatti Refrigeration Service provides expert air cooler motor repair and replacement in Dharwad for all cooler brands. Our technicians diagnose motor problems accurately: a burnt motor winding (requiring rewinding or replacement), a failed bearing causing grinding noise, a faulty motor capacitor preventing start-up, or a seized shaft. We repair or replace motors using genuine or high-quality OEM-compatible parts matched to your cooler's specifications. After replacement, we verify full airflow and cooling performance. Whether it's a small desert cooler or a large tower cooler, we service all types and brands throughout Dharwad.",
    symptoms: [
      "Fan blades not rotating or rotating very slowly",
      "Cooler making loud grinding or buzzing noise",
      "Cooler starting briefly then stopping",
      "Burning smell from the cooler motor",
      "Motor very hot to the touch",
      "Cooler vibrating excessively during operation",
    ],
    whatIsIncluded: [
      "Motor winding test and burn diagnosis",
      "Bearing condition inspection",
      "Capacitor testing and replacement",
      "Motor rewinding (where feasible)",
      "Complete motor replacement with matched unit",
      "Shaft alignment and fan blade balancing after replacement",
      "Full airflow test post-repair",
    ],
    brands: ["Symphony", "Bajaj", "Crompton", "Orient", "Kenstar", "Havells", "Usha", "Voltas", "Cello"],
    estimatedTime: "1–3 hours",
    faqs: [
      { question: "How much does air cooler motor replacement cost in Dharwad?", answer: "Motor replacement cost depends on the cooler brand, motor type, and RPM specification. We provide a transparent quote after diagnosis. WhatsApp +91-7899472430 for an estimate." },
      { question: "Can an air cooler motor be rewound instead of replaced in Dharwad?", answer: "Yes, motor rewinding is possible for certain motor types and is often more economical than full replacement. Our technicians assess whether rewinding is feasible for your specific motor." },
      { question: "Why is my air cooler motor making a loud noise in Dharwad?", answer: "Loud grinding or humming from the motor usually indicates bearing failure. A worn bearing needs replacement before it seizes completely and causes more damage." },
      { question: "My air cooler fan is not rotating at all in Dharwad. Is it the motor?", answer: "A completely still fan could be a burned motor, failed capacitor, or a seized bearing. We test motor and capacitor separately — often a capacitor replacement (more affordable) fixes the issue." },
      { question: "Do you repair air cooler motors at home in Dharwad?", answer: "Yes, our technicians provide doorstep air cooler motor repair throughout Dharwad. For rewinding, the motor must be taken to our workshop but the cooler can be dropped off and collected." },
    ],
    relatedServices: ["air-cooler-repair-service-dharwad", "ac-repair-service-dharwad", "washing-machine-repair-service-dharwad"],
    metaTitle: "Air Cooler Motor Repair Dharwad | Hosatti Refrigeration",
    metaDescription: "Air cooler motor repair & replacement in Dharwad. Bearing, capacitor & winding faults. All brands. Genuine parts. Call +91-7899472430 today!",
    keywords: ["air cooler motor repair Dharwad", "cooler motor replacement Dharwad", "cooler fan not working Dharwad", "cooler motor burnt Dharwad", "air cooler motor service Dharwad"],
    image: "/services/Air Cooler Motor Repair & Replacement.webp",
    whatsappMessage: "Hello Hosatti Refrigeration Service!\n\nI need Air Cooler Motor Repair in Dharwad.\n\nPlease let me know your availability. Thank you!",
  },
];

/** Get service by slug */
export function getServiceBySlug(slug: string): ServiceData | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

/** Get services by category */
export function getServicesByCategory(category: ServiceCategory): ServiceData[] {
  return SERVICES.filter((s) => s.category === category);
}

export const SERVICE_CATEGORIES: Record<ServiceCategory, string> = {
  ac: "Air Conditioner (AC)",
  refrigerator: "Refrigerator",
  "washing-machine": "Washing Machine",
  "air-cooler": "Air Cooler",
};
